Configure podman 5 on Ubuntu 26.04 to use NAT-ed pasta bridge.
Addressing
The ipa-server-install command failed, exception:
ScriptError: The host name ipa.example.test does not match the primary host name runnervmrd89b.dtyrjvhj1jdubpegzc4liecpve.ex.internal.cloudapp.net.

when running

docker=podman tests/run-partial-tests.sh Dockerfile....

because by default /etc/hosts contains two lines for the same
IP address like

127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
10.1.0.212      runnervmrd89b.dtyrjvhj1jdubpegzc4liecpve.ex.internal.cloudapp.net runnervmrd89b
169.254.1.2     host.containers.internal host.docker.internal
10.1.0.212      ipa.example.test freeipa-server-container-almalinux-10

and getent hosts 10.1.0.212 returns only the first one.

https://blog.podman.io/2024/03/podman-5-0-breaking-changes-in-detail/