Handle config files that are no longer present in new rpm versions.
Addressing
IPA server upgrade failed: Inspect /var/log/ipaupgrade.log and run command ipa-server-upgrade manually.
Unexpected error - see /var/log/ipaupgrade.log for details:
CalledProcessError: CalledProcessError(Command ['/bin/systemctl', 'restart', 'gssproxy.service'] returned non-zero exit status 1: 'Job for gssproxy.service failed because the control process exited with error code.\nSee "systemctl status gssproxy.service" and "journalctl -xeu gssproxy.service" for details.\n')

due to
gssproxy[1779]: network-fs-clients sets allow_any_uid with the same socket, selinux_context, and program as nfs-client!
gssproxy[1779]: Error reading configuration 1: Operation not permitted

when upgrading to Fedora 37 where /etc/gssproxy/99-nfs-client.conf
got renamed to /etc/gssproxy/99-network-fs-clients.conf.