With rootless podman containers, volume directory does not have content owned by root.
Addressing
Error: relabel failed "/tmp/freeipa-test-903638/data": failed to set file label on /tmp/freeipa-test-903638/data/build-id: operation not permitted