Add `rhel-domainname.service` to container
Fix error running `ipa-client-install`, where
`rhel-domainname.service` doesn't exist:

```
Traceback (most recent call last):
  File "/usr/sbin/ipa-client-install", line 3102, in <module>
    sys.exit(main())
  File "/usr/sbin/ipa-client-install", line 3083, in main
    rval = install(options, env, fstore, statestore)
  File "/usr/sbin/ipa-client-install", line 3043, in install
    configure_nisdomain(options=options, domain=cli_domain)
  File "/usr/sbin/ipa-client-install", line 1508, in configure_nisdomain
    services.knownservices.domainname.restart()
  File "/usr/lib/python2.7/site-packages/ipaplatform/base/services.py", line 314, in restart
    capture_output=capture_output)
  File "/usr/lib/python2.7/site-packages/ipapython/ipautil.py", line 373, in run
    raise CalledProcessError(p.returncode, arg_string, stdout)
subprocess.CalledProcessError: Command ''/bin/systemctl' 'restart' 'rhel-domainname.service'' returned non-zero exit status 2
```