Update ownership of /data content based on the template.
Addressing

IPA server upgrade failed: Inspect /var/log/ipaupgrade.log and run command ipa-server-upgrade manually.
Unexpected error - see /var/log/ipaupgrade.log for details:
CalledProcessError: CalledProcessError(Command ['/bin/systemctl', 'restart', 'sssd.service'] returned non-zero exit status 1: 'Job for sssd.service failed because the control process exited with error code.\nSee "systemctl status sssd.service" and "journalctl -xeu sssd.service" for details.\n')

when upgrading from Fedora 40 to rawhide where sssd now runs
as sssd:sssd instead of root.