Workaround 1409786 - dirsrv needs to be running and ipactl seems to start it.
Addressing
	Starting external process
	args=/usr/sbin/pkispawn -s CA -f /tmp/tmppPd_zA
	Process finished, return code=1
	stdout=Log file: /var/log/pki/pki-ca-spawn.20170103172853.log
Loading deployment configuration from /tmp/tmppPd_zA.
ERROR:  Unable to access directory server: Can't contact LDAP server