Workaround https://bugzilla.redhat.com/show_bug.cgi?id=2344322.
Addressing
Failed to resolve the transaction:
Problem: systemd-257.2-17.fc42.i686 from rawhide has inferior architecture
  - package tomcat-1:9.0.98-1.fc42.noarch from rawhide requires systemd, but none of the providers can be installed
  - problem with installed package
  - installed package systemd-standalone-sysusers-257.2-17.fc42.x86_64 conflicts with systemd provided by systemd-257.2-17.fc42.x86_64 from rawhide
  - package systemd-257.2-17.fc42.x86_64 from rawhide conflicts with systemd-standalone-sysusers provided by systemd-standalone-sysusers-257.2-17.fc42.x86_64 from rawhide
  - package dogtag-pki-server-11.6.0-0.3.alpha1.fc42.noarch from rawhide requires tomcat >= 1:9.0.62, but none of the providers can be installed
  - package dogtag-pki-ca-11.6.0-0.3.alpha1.fc42.noarch from rawhide requires dogtag-pki-server = 11.6.0-0.3.alpha1.fc42, but none of the providers can be installed
  - package dogtag-pki-ca-11.6.0-0.3.alpha1.fc42.noarch from rawhide requires mvn(org.dogtagpki.pki:pki-server) = 11.6.0.SNAPSHOT, but none of the providers can be installed
  - package freeipa-server-4.12.2-9.fc42.x86_64 from rawhide requires pki-ca >= 10.10.5, but none of the providers can be installed
  - conflicting requests
You can try to add to command line:
  --allowerasing to allow removing of installed packages to resolve problems
  --skip-broken to skip uninstallable packages
Error: building at STEP "RUN dnf upgrade -y --setopt=install_weak_deps=False 	&& dnf install -y --setopt=install_weak_deps=False freeipa-server freeipa-server-dns freeipa-server-trust-ad freeipa-healthcheck freeipa-client-epn patch 	&& dnf clean all": while running runtime: exit status 1