Additional workaround https://bugzilla.redhat.com/show_bug.cgi?id=1615948.
The PATH used by rpm scriptlets is defined in /usr/lib/rpm/macros to
	PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin

With https://fedoraproject.org/wiki/Changes/Unify_bin_and_sbin there is
now no difference among the first four locations:

	$ for i in /sbin /bin /usr/sbin /usr/bin ; do ls -dl $i ; done
	lrwxrwxrwx. 1 root root 8 Jan 16 00:00 /sbin -> usr/sbin
	lrwxrwxrwx. 1 root root 7 Jan 16 00:00 /bin -> usr/bin
	lrwxrwxrwx. 1 root root 3 Feb  6 06:32 /usr/sbin -> bin
	dr-xr-xr-x. 2 root root 12288 Feb  6 06:32 /usr/bin

That means that we have no way of putting the systemd-machine-id-setup
override to a location earlier in the PATH unless we specifically configure
the path (/usr/local/bin in this case) for the transaction.

Addressing
STEP 15/19: RUN test -f /etc/machine-id && ! test -s /etc/machine-id
Error: building at STEP "RUN test -f /etc/machine-id && ! test -s /etc/machine-id": while running runtime: exit status 1