Revert "The /run/lock seems no longer needed for dnf installation." on Fedora 25.
While dnf does not fail, opencryptoki will not get installed without /run/lock.

Addressing
  Installing  : opencryptoki-3.6.2-1.fc25.x86_64                         83/382
error: unpacking of archive failed on file /var/lock/opencryptoki: cpio: mkdir
error: opencryptoki-3.6.2-1.fc25.x86_64: install failed

This brings back part of commit 2d095813ef645562af848a45197ab0d4a49742e4.